suppliesproject/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
# ↓ SignupViewのインポートを追加
from .views import SignupView

app_name = 'accounts' 

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # ↓この行を追加
    path('signup/', SignupView.as_view(), name='signup'),

]

suppliesproject/supplies/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('supplies/', views.ListSuppliesView.as_view(), name='list-supplies'),
    path('supplies/<int:pk>/detail/', views.DetailSuppliesView.as_view(), name='detail-supplies'),
    path('supplies/create/', views.CreateSuppliesView.as_view(), name='create-supplies'),
    path('supplies/<int:pk>/update/', views.UpdateSuppliesView.as_view(), name='update-supplies'),
    path('supplies/<int:pk>/delete/', views.DeleteSuppliesView.as_view(), name='delete-supplies'),
    path('supplies/<int:supplies_id>/review/', views.CreateReviewView.as_view(), name='create-review'),
    path('', views.index_view, name='index'),
    path('review/<int:pk>/delete/', views.DeleteReviewView.as_view(), name='delete-review'),  

]

suppliesproject/suppliesproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('supplies.urls')), 
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

suppliesproject/accounts/models.py
from django.db import models

# Create your models here.

suppliesproject/supplies/models.py
from django.db import models

# Create your models here.
CATEGORY = (
    ('tool', '道具'),
    ('consumable', '消耗品'),
    ('other', 'その他')
)

RATE_CHOICES = (
    (1,'★☆☆☆☆'),
    (2,'★★☆☆☆'),
    (3,'★★★☆☆'),
    (4,'★★★★☆'),
    (5,'★★★★★'),
)


class Supplies(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    thumbnail = models.ImageField(null=True, blank=True)
    category = models.CharField(
        max_length=100,
        choices = CATEGORY
    )
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Review(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    rate = models.IntegerField(choices=RATE_CHOICES)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    supplies = models.ForeignKey(Supplies,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

suppliesproject/accounts/views.py
from django.shortcuts import render

# ↓ ここから追加（SignupViewに必要なインポートを追加）
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
# ↑ ここまで追加（SignupViewに必要なインポートを追加）

# Create your views here.

# ↓ここから追加（SignupViewを追加）
class SignupView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('login')
# ↑ここまで追加（SignupViewを追加）

suppliesproject/supplies/views.py
from django.shortcuts import render
# ↓ reverse関数をインポートする記述を追記
from django.urls import reverse,reverse_lazy
# ↓ UpdateViewをインポートする記述を追記
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
# ↓ Reviewをインポートする記述を追記
from .models import Supplies,Review
# ↓ PermissionDeniedをインポートする記述を追記
from django.core.exceptions import PermissionDenied

from django.contrib.auth.mixins import LoginRequiredMixin
from .models import RATE_CHOICES

from django.db.models import Avg
from django.core.paginator import Paginator
from .consts import ITEM_PER_PAGE


# Create your views here.
class ListSuppliesView(LoginRequiredMixin,ListView):
    model = Supplies
    template_name = 'supplies/list.html'

class DetailSuppliesView(LoginRequiredMixin,DetailView):
    model = Supplies
    template_name = 'supplies/detail.html'
    # ↓ここから追記
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rate_choices'] = RATE_CHOICES
        return context
    # ↑ここまで追記

class CreateSuppliesView(LoginRequiredMixin,CreateView):
    template_name = 'supplies/create.html'
    model = Supplies
    fields = ('title', 'description', 'category', 'thumbnail')
    success_url = reverse_lazy('list-supplies')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class UpdateSuppliesView(LoginRequiredMixin,UpdateView):
    template_name = 'supplies/update.html'
    model = Supplies
    fields = ('title', 'description', 'category', 'thumbnail')

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)

        if obj.user != self.request.user:
            raise PermissionDenied

        return obj
    
    def get_success_url(self):
        return reverse('detail-supplies', kwargs={'pk': self.object.id})

class DeleteSuppliesView(LoginRequiredMixin,DeleteView):
    template_name = 'supplies/delete_confirm.html'
    model = Supplies
    success_url = reverse_lazy('list-supplies')

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)

        if obj.user != self.request.user:
            raise PermissionDenied
        
        return obj

class CreateReviewView(LoginRequiredMixin, CreateView):
    model = Review
    fields = ('title', 'description', 'rate', 'supplies')
    template_name = 'supplies/review/create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['supplies'] = Supplies.objects.get(pk=self.kwargs['supplies_id'])
        context['rate_choices'] = RATE_CHOICES
        return context
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('detail-supplies', kwargs={'pk': self.object.supplies.id})

class DeleteReviewView(LoginRequiredMixin, DeleteView):
    model = Review
    template_name = 'supplies/review/delete_confirm.html'
    success_url = reverse_lazy('list-supplies')

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.user != self.request.user:
            raise PermissionDenied
        return obj

def index_view(request):
    object_list = Supplies.objects.order_by('-id')
    ranking_list = Supplies.objects.annotate(avg_rating=Avg('review__rate')).order_by('-avg_rating')

    paginator = Paginator(ranking_list, ITEM_PER_PAGE)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.page(page_number)

    return render(
        request,
        'supplies/index.html',
        {'object_list': object_list, 'ranking_list': ranking_list, 'page_obj': page_obj},
    )

suppliesproject/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %} アカウント作成 {% endblock %}
{% block h1 %} アカウント作成 {% endblock %}
{% block content %}
<form method="POST" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    <input type="text" id="username" name="username" class="form-control my-4" placeholder="ユーザーID">
    <input type="password" id="password1" name="password1" class="form-control mt-4" placeholder="パスワード">
    <input type="password" id="password2" name="password2" class="form-control mt-4" placeholder="パスワード確認用">
    <small class="mb-2 small text-danger d-block text-start">パスワードは8文字以上で設定してください。</small>
    {% if form.errors %}
        <span class="mb-2 small text-danger d-block text-start">利用できないユーザーIDやパスワードの可能性があります。入力内容を再度ご確認ください。</span>
    {% endif %}
    <button type="submit" class="btn btn-success m-2">アカウント作成</button>
</form>
{% endblock %}

suppliesproject/supplies/templates/supplies/components/pagination.html
{% if page_obj.has_previous %}
    <a href="?page=1">&laquo; 最初</a>
    <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

<span class="current">
    {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
</span>

{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">次へ</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">最後 &raquo;</a>
{% endif %}

suppliesproject/supplies/templates/supplies/create.html
{% extends 'base.html' %}

{% block title %} 備品作成 {% endblock %}

{% block content %}
<form method="POST" enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">{% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="作成する">
</form>
{% endblock content %}

suppliesproject/supplies/templates/supplies/delete_confirm.html
{% extends 'base.html' %}

{% block title %} 備品削除確認 {% endblock %}

{% block content %}
<form method="POST" enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">{% csrf_token %}
    {{form.as_p}}
    <button type="submit">{{object.title}}を削除する</button>
</form>
{% endblock %}

suppliesproject/supplies/templates/supplies/detail.html
{% extends 'base.html' %}
{% block title %} {{ object.title }} {% endblock %}
{% block h1 %} 備品詳細 {% endblock %}

{% block content %}
<div class="p-4 m-4 bg-light border border-success rounded">
  <h2 class="text-success">{{ object.title }}</h2>
  <p id="item_description">{{ object.description }}</p>

  <!-- ↓ ここから追記 -->
  <div class="border p-4 mb-2">
    {% for review in object.review_set.all %}
    <div>
      <h3 class="h4">{{ review.title }}</h3>
      <div class="px-2">
        <span>(投稿ユーザー: {{ review.user.username }} )</span>
        <h6>評価:
        {% for k,v in rate_choices %}
          {% if k == review.rate %}
            {{ v }}
          {% endif %}
        {% endfor %}
        </h6>
        <p>{{ review.description }}</p>
        {% if review.user == request.user %}
        <a href = "{% url 'delete-review' review.pk %}" class="btn btn-primary btn-sm">削除</a>
        {% endif %}
      </div>
    </div>
    {% endfor %}
  </div>
  <!-- ↓ ここまで追記 -->

  <div class="mt-3">
    <a href = "{% url 'update-supplies' object.pk %}" class="btn btn-primary">編集する</a>
    <a href = "{% url 'delete-supplies' object.pk %}" class="btn btn-primary">削除する</a>
    <a href = "{% url 'create-review' object.pk %}" class="btn btn-primary">レビューする</a>
    <h6 class="card-title">{{ object.category }}</h6>
  </div>
</div>
{% endblock content %}

suppliesproject/supplies/templates/supplies/index.html
{% extends 'base.html' %}

{% block title %} 備品一覧 {% endblock %}
{% block h1 %} 備品一覧 {% endblock %}

{% block content %}
<div class="row">
  <div class="col-9">
    {% for item in object_list %}
      <div class="p-4 m-4 bg-light border border-success rounded">
        <h2 class="text-success">{{ item.title }}</h2>
        {% if item.thumbnail %}
          <img src="{{ item.thumbnail.url }}" class="img-thumbnail" alt="Thumbnail">
        {% else %}
          <p>---画像準備中---</p>
        {% endif %}

        <h6>カテゴリ：{{ item.category }}</h6>
        <div class="mt-3">
          <a href="{% url 'detail-supplies' item.pk %}">詳細へ</a>
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="col-3">
    <h2>評価TOP2</h2>
    {% for ranking_supplies in page_obj %}
      <div class="p-4 m-4 bg-light border border-success rounded">
        <h3 class="text-success h5">{{ ranking_supplies.title }}</h3>
        {% if ranking_supplies.thumbnail %}
          <img src="{{ ranking_supplies.thumbnail.url }}" class="img-thumbnail"/>
        {% else %}
         <p>---画像準備中---</p>
        {% endif %}
        <h6>評価：{{ ranking_supplies.avg_rating|floatformat:2 }}点</h6>
        <a href="{% url 'detail-supplies' ranking_supplies.id %}">詳細を見る</a>
      </div>
    {% endfor %}
    {% include 'supplies/components/pagination.html' %}
  </div>
</div>
{% endblock %}

suppliesproject/supplies/templates/supplies/list.html
{% extends 'base.html' %}

{% block title %} 備品一覧 {% endblock %}
{% block h1 %} 備品一覧 {% endblock %}

{% block content %}

{% for item in object_list %}
<div class="p-4 m-4 bg-light border border-success rounded">
<h2 class="text-success">{{ item.title }}</h2>
<h6>カテゴリ：{{ item.category }}</h6>
<div class="mt-3">
    <a href="{% url 'detail-supplies' item.pk %}">詳細へ</a>
</div>
</div>
{% endfor %}

{% endblock content %}

suppliesproject/supplies/templates/supplies/review/create.html
{% extends 'base.html' %}

{% block title %} レビュー投稿 {% endblock %}
{% block h1 %} レビュー投稿 {% endblock %}

{% block content %}
 <form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    <label>
        対象備品
    </label>
    <input class="form-control" value="{{ supplies.title }}" readonly>
    <label>
        タイトル
    </label>
    <input class="form-control" name="title">
    <label>
        本文
    </label>
    <textarea class="form-control" name="description" rows="3"></textarea>
    <label>
        評価
    </label>
    <select class="form-control" name="rate">
        {% for value, display in rate_choices %}
        <option value="{{ value }}">{{ display }}</option>
        {% endfor %}
    </select>
    <input type="hidden" name="supplies" value="{{ supplies.id }}">
    <button type="submit" class="btn btn-success mt-4">投稿する</button>
</form>
{% endblock %}

suppliesproject/supplies/templates/supplies/review/delete_confirm.html
{% extends 'base.html' %}

{% block title %} レビュー削除 {% endblock %}

{% block content %}
<form method="POST">{% csrf_token %}
    {{form.as_p}}
    <button type="submit">このレビューを削除する</button>
</form>
{% endblock content %}

suppliesproject/supplies/templates/supplies/update.html
{% extends 'base.html' %}

{% block title %} 備品修正 {% endblock %}

{% block content %}
<form method="POST" enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">{% csrf_token %}
    {{form.as_p}}
    <button type="submit">修正する</button>
</form>
{% endblock %}

suppliesproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %} {% endblock title %}| 社内備品管理システム</title>
    <link rel="stylesheet" type="text/css" href="{% static 'supplies/css/style.css' %}">
</head>
<body>
    
    <nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #006633;">
      {% if request.user.is_authenticated %}
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}"><b>社内備品<br>管理システム</b></a>
          <div class="collapse navbar-collapse" id="navbarScroll">
            
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'list-supplies' %}">備品一覧</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'create-supplies' %}">備品登録</a>
              </li>
            </ul>
            <li class="nav-item">
              <form action="{% url 'accounts:logout' %}" method="post">{% csrf_token %}
                <button type="submit" class="btn btn-link nav-link">ログアウト</button>
              </form>
            <!-- <a class="nav-link" href="{% url 'accounts:logout' %}">ログアウト</a> -->
            </li>
      {% else %}
      <div class="container-fluid">
        <b>社内備品<br>管理システム</b>
        <div class="collapse navbar-collapse" id="navbarScroll">

            <ul class="navbar-nav ms-auto">
            
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:login' %}">ログイン</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:signup' %}">サインアップ</a>
              </li>
              
          </ul>
      {% endif %}
          </div>
        </div>
      </nav>

    <div class="p-4">
        <h1>{% block h1 %} {% endblock %}</h1>
        {% block content %} {% endblock content %}
    </div>
</body>
</html>

suppliesproject/templates/signup.html
{% extends 'base.html' %}

{% block title %} アカウント作成 {% endblock %}
{% block h1 %} アカウント作成 {% endblock %}
{% block content %}
<form method="POST" class="p-4 m-4 bg-light border border-success rounded form-group">
    {% csrf_token %}
    <input type="text" id="username" name="username" class="form-control my-4" placeholder="ユーザーID">
    <input type="password" id="password1" name="password1" class="form-control mt-4" placeholder="パスワード">
    <input type="password" id="password2" name="password2" class="form-control mt-4" placeholder="パスワード確認用">
    <small class="mb-2 small text-danger d-block text-start">パスワードは8文字以上で設定してください。</small>
    {% if form.errors %}
        <span class="mb-2 small text-danger d-block text-start">利用できないユーザーIDやパスワードの可能性があります。入力内容を再度ご確認ください。</span>
    {% endif %}
    <button type="submit" class="btn btn-success m-2">アカウント作成</button>
</form>
{% endblock %}